# Generated by Django 5.2.1 on 2025-05-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='users/')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('exp', models.BigIntegerField(default=0)),
                ('spended_time', models.BigIntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course_lvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('exp', models.BigIntegerField(default=0)),
                ('spended_time', models.BigIntegerField(default=0)),
                ('text', models.CharField()),
            ],
        ),
    ]
