# Generated by Django 5.2.1 on 2025-05-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('number', models.IntegerField(default=1)),
                ('question', models.CharField(default='', max_length=255)),
                ('variant1', models.CharField(default='', max_length=255)),
                ('variant2', models.CharField(default='', max_length=255)),
                ('variant3', models.CharField(default='', max_length=255)),
                ('right_variant', models.CharField(default='', max_length=255)),
                ('exp', models.BigIntegerField(default=0)),
                ('spended_time', models.BigIntegerField(default=0)),
                ('text', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='tests_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course_lvl',
            name='course_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course_lvl',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course_lvl',
            name='theme',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course_lvl',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course_lvl',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
