# Generated by Django 5.2.1 on 2025-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_course_test_course_full_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_test',
            old_name='question',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='course_test',
            name='text',
        ),
        migrations.AlterField(
            model_name='course_lvl',
            name='text',
            field=models.CharField(default=''),
        ),
    ]
