# Generated by Django 5.2.1 on 2025-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_question_course_test_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(default='начальный', max_length=255),
        ),
    ]
