# Generated by Django 5.2.1 on 2025-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_course_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_lvl',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
