# Generated by Django 5.2.1 on 2025-05-14 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_rename_name_user_full_name_remove_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 15, 23, 26, 678965)),
        ),
    ]
