# Generated by Django 5.2.1 on 2025-05-14 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0003_user_registred_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_lvls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('exp', models.BigIntegerField(default=0)),
                ('spended_time', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='achivement',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='achivement',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_achivements',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_achivements',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_achivements',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='exp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='lvl',
            field=models.CharField(default='начальный', max_length=255),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='passed_lvls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='spended_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='exp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='spended_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 16, 0, 21, 218076)),
        ),
    ]
