# Generated by Django 5.2.1 on 2025-05-14 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0005_rename_lvl_user_courses_difficulty_user_courses_lvls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_courses',
            name='precent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 17, 54, 57, 522034)),
        ),
    ]
