# Generated by Django 5.2.1 on 2025-05-14 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0006_user_courses_precent_alter_user_registred_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_courses',
            old_name='precent',
            new_name='percent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lvl',
        ),
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.BigIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 18, 56, 27, 802981)),
        ),
    ]
