# Generated by Django 5.2.1 on 2025-05-14 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0007_rename_precent_user_courses_percent_remove_user_lvl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/avatar.png', upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 22, 33, 47, 844136)),
        ),
    ]
