# Generated by Django 5.2.1 on 2025-05-14 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0008_alter_user_image_alter_user_registred_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='media/users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 15, 0, 52, 47, 113136)),
        ),
    ]
