# Generated by Django 5.2.1 on 2025-05-15 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0011_achivement_exp_user_achivements_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_achivements',
            name='passed_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 16, 0, 50, 11, 311173)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 16, 0, 50, 11, 309180)),
        ),
    ]
