# Generated by Django 5.2.1 on 2025-05-16 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0015_alter_user_registred_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_lvls',
            old_name='description',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='user_tests',
            old_name='description',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='user_lvls',
            name='course_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_lvls',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user_lvls',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_lvls',
            name='text',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='user_lvls',
            name='theme',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='course_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='questions',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 16, 21, 2, 41, 575191)),
        ),
        migrations.AlterField(
            model_name='user_achivements',
            name='passed_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 16, 21, 2, 41, 577189)),
        ),
    ]
