# Generated by Django 5.2.1 on 2025-05-16 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0016_rename_description_user_lvls_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_courses',
            name='full_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 16, 21, 20, 16, 87239)),
        ),
        migrations.AlterField(
            model_name='user_achivements',
            name='passed_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 16, 21, 20, 16, 87239)),
        ),
    ]
