# Generated by Django 5.2.1 on 2025-05-16 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0017_user_courses_full_description_user_courses_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 1, 21, 57, 731544)),
        ),
        migrations.AlterField(
            model_name='user_achivements',
            name='passed_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 1, 21, 57, 736596)),
        ),
    ]
