# Generated by Django 5.2.1 on 2025-05-16 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0019_user_courses_category_alter_user_registred_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 1, 31, 53, 181509)),
        ),
        migrations.AlterField(
            model_name='user_achivements',
            name='passed_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 1, 31, 53, 181509)),
        ),
        migrations.AlterField(
            model_name='user_achivements',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_courses',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_lvls',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_tests',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
