# Generated by Django 5.2.1 on 2025-05-17 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0022_alter_user_registred_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registred_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 22, 51, 56, 445572)),
        ),
        migrations.AlterField(
            model_name='user_achivements',
            name='passed_time',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 22, 51, 56, 445572)),
        ),
    ]
